# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/
# Version of the config file format
version: 1

run:
  tests: false
  timeout: 5m

linters:
  enable:
    - bodyclose
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude ui and utils directories
    - path: "^ui/"
      linters:
        - ".*"
    - path: "^utils/"
      linters:
        - ".*"
    # Exclude wrapcheck from test files
    - path: "_test\\.go"
      linters:
        - wrapcheck