run:
  tests: false
  timeout: 5m

linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-use-default: false
  exclude-dirs:
    - ui
    - utils
