name: build

on: [push, pull_request]

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Install audio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      
      - name: Install audio dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      
      - name: Install audio dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          # macOS has CoreAudio built-in, no additional dependencies needed
          echo "macOS audio dependencies already available"
      
      - name: Install audio dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          # Windows has WASAPI/DirectSound built-in
          echo "Windows audio dependencies already available"

      - run: go mod download
      - run: go build -v ./...
      - run: go test -race ./...

  semgrep:
    uses: charmbracelet/meta/.github/workflows/semgrep.yml@main

  ruleguard:
    uses: charmbracelet/meta/.github/workflows/ruleguard.yml@main
    with:
      go-version: stable