name: lint
on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      
      - name: Install audio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      
      - name: Download dependencies
        run: |
          go mod download
          go mod verify
      
      - name: Build to generate export data
        run: |
          go build -v ./...
        continue-on-error: true
      
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      
      - name: Run golangci-lint
        run: |
          golangci-lint run --issues-exit-code=0 --timeout=5m ./...
        continue-on-error: true
